stages:
  - test
  - build
  - deploy

variables:
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
#  GIT_STRATEGY: clone

test_services:
  stage: test
  script:
   - echo "TESTING API"
   - flutter test test/services
  only:
   - staging
  when: manual

build_android_debug:
  stage: build
  before_script:
    - flutter pub get
    - flutter clean
    - echo $TEST_KEY
    - echo $KEYSTORE | base64 -D -o android/release-key.keystore
    - echo $KEYSTORE_PROPERTIES | base64 -D -o android/keystore.properties
    - echo $GOOGLE_SERVICES | base64 -D -o android/app/google-services.json
  script:
    - flutter build apk --debug
  artifacts:
    paths:
      - build/app/outputs/apk/debug/app-debug.apk
  only:
    - develop
  when: manual

build_ios_debug:
  stage: build
  before_script:
    - flutter pub get
    - flutter clean
    - echo $GOOGLE_PLIST | base64 -D -o ios/Runner/GoogleService-Info.plist
    - cd ios/ && pod install && cd ../
  script:
    - flutter build ios --debug --no-codesign
  artifacts:
    paths:
      - build/ios/iphoneos/Runner.app
  only:
    - develop
  when: manual

deploy_android_alpha:
  stage: deploy
  before_script:
    - flutter packages get
    - flutter clean
    - echo $TEST_KEY
    - echo $KEYSTORE | base64 -D -o android/release-key.keystore
    - echo $KEYSTORE_PROPERTIES | base64 -D -o android/keystore.properties
    - echo $GOOGLE_SERVICES | base64 -D -o android/app/google-services.json
    - echo $GOOGLE_API | base64 -D -o android/google_service_account_api.json
  script:
    - flutter build appbundle --release
    - cd android/ && fastlane deploy_alpha && cd ../
  artifacts:
    paths:
      - build/app/outputs/bundle/release/app.aab
  only:
    - staging

deploy_ios_testflight:
  stage: deploy
  before_script:
    - flutter pub get
    - flutter clean
    - echo $TEST_KEY
    - echo $GOOGLE_PLIST | base64 -D -o ios/Runner/GoogleService-Info.plist
    - cd ios/ && pod install && cd ../
  script:
    - flutter build ios --release --no-codesign
    - cd ios/ && fastlane ios beta && cd ../
  artifacts:
    paths:
      - build/ios/iphoneos/Runner.app
  only:
    - staging


deploy_android_prod:
  stage: deploy
  before_script:
    - flutter packages get
    - flutter clean
    - echo $TEST_KEY
    - echo $KEYSTORE | base64 -D -o android/release-key.keystore
    - echo $KEYSTORE_PROPERTIES | base64 -D -o android/keystore.properties
    - echo $GOOGLE_SERVICES | base64 -D -o android/app/google-services.json
    - echo $GOOGLE_API | base64 -D -o android/google_service_account_api.json
  script:
    - flutter build appbundle --release
    - cd android/ && fastlane deploy_prod && cd ../
  artifacts:
    paths:
      - build/app/outputs/bundle/release/app.aab
  only:
    - master
  when: manual
